services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '80:80'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=books
      - MYSQL_USER=books
      - MYSQL_PASSWORD=password
    ports:
      - 33060:3306